# Tivan configuration

# Tivan is entirely plugin driven. All metrics are gathered from the
# declared plugins.

# Even if a plugin has no configuration, it must be declared in here
# to be active. Declaring a plugin means just specifying the name
# as a section with no variables.

# Configuration for influxdb server to send metrics to
# [influxdb]
# url = "http://10.20.2.4"
# username = "tivan"
# password = "metricsmetricsmetricsmetrics"
# database = "tivan"
# user_agent = "tivan"
# tags = { "dc": "us-east-1" }

# Tags can also be specified via a normal map, but only one form at a time:

# [influxdb.tags]
# dc = "us-east-1"

# PLUGINS

# Read metrics about cpu usage
[cpu]
  # no configuration

# Read metrics about disk usage by mount point
[disk]
  # no configuration

# Read metrics about docker containers
[docker]
  # no configuration

# Read metrics about disk IO by device
[io]
  # no configuration

# Read metrics about memory usage
[mem]
  # no configuration

# Read metrics from one or many mysql servers
[mysql]

# specify servers via a url matching:
#  [username[:password]@][protocol[(address)]]/[?tls=[true|false|skip-verify]]
#
# If no servers are specified, then localhost is used as the host.
servers = ["localhost"]

# Read metrics about network interface usage
[net]
  # no configuration

# Read metrics from one or many postgresql servers
[postgresql]

# specify servers via an array of tables
[[postgresql.servers]]

# specify address via a url matching:
#   postgres://[pqgotest[:password]]@localhost?sslmode=[disable|verify-ca|verify-full]
# or a simple string:
#   host=localhost user=pqotest password=... sslmode=...
# 
# All connection parameters are optional. By default, the host is localhost
# and the user is the currently running user. For localhost, we default
# to sslmode=disable as well.
# 

address = "sslmode=disable"

# A list of databases to pull metrics about. If not specified, metrics for all
# databases are gathered.

# databases = ["app_production", "blah_testing"]

# [[postgresql.servers]]
# address = "influx@remoteserver"

# Read metrics from one or many redis servers
[redis]

# An array of address to gather stats about. Specify an ip on hostname
# with optional port. ie localhost, 10.10.3.33:18832, etc.
#
# If no servers are specified, then localhost is used as the host.
servers = ["localhost"]

# Read metrics about swap memory usage
[swap]
  # no configuration

# Read metrics about system load
[system]
  # no configuration

